# Generated by Django 5.2.3 on 2025-07-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchitem',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
