# Generated by Django 5.2.3 on 2025-07-06 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_watchitem_poster_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actor',
            new_name='Cast',
        ),
        migrations.RenameField(
            model_name='watchitem',
            old_name='actor',
            new_name='cast',
        ),
    ]
